/* Traducción del sitio. Para añadir texto nuevo: agrega la frase en inglés
   como clave y su versión en español como valor. */
window.ES = {
"Skip to main content": "Ir al contenido principal",
"Short Films": "Cortometrajes",
"Music Video": "Videoclips",
"music video": "videoclips",
"Work in progress": "En desarrollo",
"work in progress": "en desarrollo",
"About US": "Sobre nosotros",
"Contacts": "Contacto",
"contact us": "contacto",
"See all ↗": "Ver todos ↗",
"See more ↗": "Ver más ↗",
"Watch now": "Ver ahora",
"Trailer": "Tráiler",
"06 films": "06 cortometrajes",
"06 videos": "06 videoclips",
"04 films in development": "04 películas en desarrollo",
"about dEUSeXmACHINAfilms": "sobre dEUSeXmACHINAfilms",
"Screenings": "Exhibiciones",
"Award": "Premio",
"Winner": "Ganador",
"Director": "Director",
"— Director": "— Director",
"To request more information, email us directly.": "Para más información, escríbenos directamente.",
"Duration: 9:19": "Duración: 9:19",
"Duration: 14:44": "Duración: 14:44",
"Duration: 09:06": "Duración: 09:06",
"Duration: 07:53": "Duración: 07:53",
"Duration: 14:18": "Duración: 14:18",
"Duration: 04:46": "Duración: 04:46",
"Documentary — Experimental": "Documental — Experimental",
"Documentary — Essay — Dance": "Documental — Ensayo — Danza",
"Essay dance documentary": "Documental de danza y ensayo",
"Co production Chile — France": "Coproducción Chile — Francia",
"Status:": "Estado:",
"Direction": "Dirección",
"DOP": "Fotografía",
"Edition": "Montaje",
"Edit": "Montaje",
"Cast": "Elenco",
"Production": "Producción",
"Music": "Música",
"Sound": "Sonido",
"Sound design": "Diseño sonoro",
"Drone": "Dron",
"Camera": "Cámara",
"Script": "Guion",
"Producers": "Productores",
"Executive producer": "Productor ejecutivo",
"Executive Producer": "Productor ejecutivo",
"Executive Production": "Producción ejecutiva",
"Also Producer": "También produce",
"Associate producer": "Productora asociada",
"General Producers": "Producción general",
"Thanks to": "Agradecimientos",
"Photo": "Fotografía fija",
"Dancers": "Bailarinas",
"Children": "Niños y niñas",
"Guides": "Guías",
"Training": "Entrenamiento",
"Transport": "Transporte",
"Finance": "Financiamiento",
"Distribution": "Distribución",
"Narrated by": "Narración",
"Performer": "Intérprete",
"Collaborators": "Colaboradores",
"Co-production": "Coproducción",
"Co-produced by": "Coproducido por",
"Co-Produced by": "Coproducido por",
"Colective authory by": "Autoría colectiva de",
"Choreographed by": "Coreografía de",
"Choreographic direction": "Dirección coreográfica",
"Scientific advice": "Asesoría científica",
"Production design": "Dirección de arte",
"Arte": "Dirección de arte",
"Stagecraft theater": "Técnica escénica",
"Stagecraft collaborator": "Colaboración técnica",
"Theater sound": "Sonido en sala",
"Suporting": "Apoyo",
"Aditional camera": "Cámara adicional",
"Cámara adicional": "Cámara adicional",
"Assistant camera": "Asistente de cámara",
"Assitant camera": "Asistente de cámara",
"Assitant direction": "Asistencia de dirección",
"Translate & Subtitles": "Traducción y subtítulos",
"Sound post production": "Postproducción de sonido",
"Post producción": "Postproducción",
"Post producción image": "Postproducción de imagen",
"Post Color / Sonido": "Postproducción de color y sonido",
"DOP & Edit": "Fotografía y montaje",
"DOP & Edition": "Fotografía y montaje",
"DOP & edition": "Fotografía y montaje",
"DOP and Editing": "Fotografía y montaje",
"DOP / Camera": "Fotografía y cámara",
"Direction, DOP & Edit": "Dirección, fotografía y montaje",
"Direction, DOP & edition": "Dirección, fotografía y montaje",
"Director, DOP & Edit": "Dirección, fotografía y montaje",
"Directed, Script, DOP & Editing by": "Dirección, guion, fotografía y montaje",
"Produced, written, edited & directed by": "Producción, guion, montaje y dirección",
"Written and directed by": "Escrita y dirigida por",
"Executive producer & direction": "Producción ejecutiva y dirección",
"Producers, Scripts": "Producción y guion",
"Producers & Script": "Producción y guion",
"Research, creation, design & performers": "Investigación, creación, diseño e intérpretes",
"Cast (Dance, writing and voices)": "Elenco (danza, escritura y voces)",
"Direction & camera": "Dirección y cámara",
"Participant": "Participante",
"Location": "Lugar",
"Amsterdam, Netherlands": "Ámsterdam, Países Bajos",
"won Best Film at DJK Fest Imagitari, Indonesia.": "ganó Mejor película en el DJK Fest Imagitari, Indonesia.",
", for the band SUBE, won the Animal and Environmental Film Festival, Mexico.": ", para la banda SUBE, ganó el Animal and Environmental Film Festival, México.",
", produced with Heidi Duckler Dance, received an honorable mention at the Mexico City Videodance Festival, and": ", producido con Heidi Duckler Dance, recibió una mención honrosa en el México City Videodance Festival, y",
"a mention for choreography at the VIII Muestra Movimiento Audiovisual.": "una mención por coreografía en la VIII Muestra Movimiento Audiovisual.",
"dEUSeXmACHINAfilms makes dance films, experimental and hybrid documentary, and music videos.": "dEUSeXmACHINAfilms hace cine de danza, documental experimental e híbrido, y videoclips.",
"Founded in 2018, working between Chile and Austria.": "Fundada en 2018, trabajando entre Chile y Austria.",
"The work has screened in thirteen countries: Chile, Argentina, Brazil, Colombia, Costa Rica, Mexico, the United States, Spain, Portugal, Italy, Romania, Indonesia and Australia.": "La obra se ha exhibido en trece países: Chile, Argentina, Brasil, Colombia, Costa Rica, México, Estados Unidos, España, Portugal, Italia, Rumania, Indonesia y Australia.",
"Before cinema, twelve years in theatre as actor, playwright and director, and producer of the stage company Turba between 2009 and 2019. He dances contemporary and contact improvisation with the company": "Antes del cine, doce años de teatro como actor, dramaturgo y director, y productor de la compañía Turba entre 2009 y 2019. Practica danza contemporánea y contacto improvisación con la compañía",
", performing in Argentina, Peru, Chile, Brazil, Canada and China.": ", con la que se ha presentado en Argentina, Perú, Chile, Brasil, Canadá y China.",
"Full biography and personal work at": "Biografía completa y trabajo personal en",
"We are fascinated by artistic experimentation. We explore nature and urbanity to create a unique cinematographic dimension, capable of creating powerful discourses that invite us to reflect on who we are and how we live.": "Nos fascina la experimentación artística. Exploramos la naturaleza y lo urbano para crear una dimensión cinematográfica propia, capaz de construir discursos potentes que invitan a pensar quiénes somos y cómo vivimos.",
"A practice by dEUSeXmACHINA films": "Una práctica de dEUSeXmACHINA films",
"The Session is where the film happens.": "La sesión es donde ocurre la película.",
"An audiovisual practice built on the encounter between a real person, a real place, a camera, movement and time.": "Una práctica audiovisual construida sobre el encuentro entre una persona real, un lugar real, una cámara, el movimiento y el tiempo.",
"The participant — usually a dancer or performer — is invited to be themselves. The location is an active part of the work. The filmmaker, who is also a dancer, responds physically to the performer with the camera.": "A quien participa —normalmente un bailarín o performer— se le invita a ser quien es. El lugar es parte activa de la obra. El cineasta, que también es bailarín, responde físicamente al intérprete con la cámara.",
"The aim is not to predetermine the film, but to create the conditions for something unexpected to happen.": "No se trata de predeterminar la película, sino de crear las condiciones para que ocurra algo inesperado.",
"We don't create everything. We create the conditions for something to happen.": "No lo creamos todo. Creamos las condiciones para que algo ocurra.",
"Visual introduction": "Introducción visual",
"The process": "El proceso",
"The sessions": "Las sesiones",
"A real person.": "Una persona real.",
"A real place.": "Un lugar real.",
"A camera.": "Una cámara.",
"Time.": "Tiempo.",
"Meet": "Encuentro",
"Two people, before anything is filmed.": "Dos personas, antes de filmar nada.",
"The agreement of a trajectory.": "El acuerdo de una trayectoria.",
"One take": "Una toma",
"An improvised sequence.": "Una secuencia improvisada.",
"Film": "Película",
"Captured presence.": "Presencia capturada.",
"Mistakes, accidents and unexpected events may become part of the work.": "Los errores, los accidentes y lo inesperado pueden volverse parte de la obra.",
"The movement exists in time.": "El movimiento existe en el tiempo.",
"Whenever appropriate, long takes and continuous shots. The dancer should not have to dance the edit.": "Cuando corresponde, planos largos y tomas continuas. El bailarín no debería tener que bailar el montaje.",
"Enter the session ↗": "Entrar a la sesión ↗",
"A person enters a place.": "Una persona entra en un lugar.",
"The camera begins to move.": "La cámara empieza a moverse.",
"Something unexpected happens.": "Ocurre algo inesperado.",
"The film emerges.": "La película emerge.",
"The Session": "The Session",
"The edited audiovisual record of the encounter. Not behind-the-scenes material: part of the work itself.": "El registro audiovisual editado del encuentro. No es material de detrás de cámara: es parte de la obra.",
"Frames from the session": "Fotogramas de la sesión",
"← All sessions": "← Todas las sesiones",
"On this beach in the South Pacific there is a platform of fossil sediments from more than 70 million years ago, when dinosaurs still lived there.": "En esta playa del Pacífico sur hay una plataforma de sedimentos fósiles de hace más de 70 millones de años, cuando allí todavía vivían dinosaurios.",
"Among the animals that survived the meteorite are some birds and snails, which continued to evolve until today.": "Entre los animales que sobrevivieron al meteorito hay aves y caracoles, que siguieron evolucionando hasta hoy.",
"“Helix Evolution” is a short film about contemplating this particular landscape, which is gradually recognized by a human who adopts the mobility of a bird.": "«Helix Evolution» es un cortometraje sobre la contemplación de este paisaje particular, reconocido poco a poco por un humano que adopta la movilidad de un ave.",
"This documentary-style dance piece invites us to reflect on and address the dangers of free market capitalism, corrupt leadership, and COVID as a response to social revolution.": "Esta pieza de danza en clave documental invita a pensar los peligros del capitalismo de libre mercado, los liderazgos corruptos y el COVID como respuesta a la revuelta social.",
"A dance/offering that is born by, with and for La Peña, a natural sanctuary located on the southern coast of the Pacific Ocean. A meeting of women discovering everything that surrounds them.": "Una danza-ofrenda que nace por, con y para La Peña, santuario natural en la costa sur del océano Pacífico. Un encuentro de mujeres descubriendo todo lo que las rodea.",
"Pandora is trapped in the city, she wants to free herself from the Box of All Evils. Pandora reflects on consumer society, she decides to break the normal course of the spaces where goods are traded, her weapon is her body, her dance.": "Pandora está atrapada en la ciudad, quiere liberarse de la Caja de Todos los Males. Pandora reflexiona sobre la sociedad de consumo y decide romper el curso normal de los espacios donde se transan las mercancías: su arma es su cuerpo, su danza.",
"In the small town of Puerto Octay, in southern Chile, every morning the students of La Redonda School begin their day with meditation. Their desire to learn through play and imagination leads them to create a magic potion that transports them to a natural sanctuary.": "En el pueblo de Puerto Octay, en el sur de Chile, cada mañana los estudiantes de la Escuela La Redonda comienzan el día meditando. Su deseo de aprender jugando e imaginando los lleva a crear una poción mágica que los transporta a un santuario natural.",
"MORAR is an invitation to stay, to remain and to allow what is already happening to pass through us. We allow ourselves to be moved by the sacred, by the whispering silence of mystery; and then, the question arises, how much distance is there between Nature and us? Does it even exist?…": "MORAR es una invitación a quedarse, a permanecer y a dejar que nos atraviese lo que ya está ocurriendo. Nos dejamos mover por lo sagrado, por el silencio susurrante del misterio; y entonces aparece la pregunta: ¿cuánta distancia hay entre la Naturaleza y nosotros? ¿Existe siquiera?…",
"A group of rebels crosses through the building of the Ministry of Culture of Chile, while the former Minister Paulina Urrutia gives voice to a reflection on the function of art in society, suggesting that the artistic phenomenon allows us to recognize ourselves and activate a powerful internal force capable of transforming reality": "Un grupo de rebeldes atraviesa el edificio del Ministerio de las Culturas de Chile, mientras la exministra Paulina Urrutia pone voz a una reflexión sobre la función del arte en la sociedad, sugiriendo que el fenómeno artístico nos permite reconocernos y activar una potente fuerza interna capaz de transformar la realidad",
"As usual, Marie enjoys her game of violence when she sculpts figures of men who embody mythological gods, until one day she senses a powerful presence in her workshop. That sleepless night, she begins the project that will obsess her: a sculpture of Medusa’s head. As she progresses, the transformation gestates within her, sculpting a new being from the depths.": "Como siempre, Marie disfruta su juego de violencia al esculpir figuras de hombres que encarnan dioses mitológicos, hasta que un día percibe una presencia poderosa en su taller. Esa noche de insomnio comienza el proyecto que la obsesionará: una escultura de la cabeza de Medusa. A medida que avanza, la transformación se gesta dentro de ella, esculpiendo un nuevo ser desde lo profundo.",
"Year 2052, Venus wakes up without memories in a city stagnant in time. She does not know if she is human or an organic robot. The absence of feelings leads her to seek emotions through perceptive experiments that generate vivid visions of her in a lush forest, a white horse and a little girl: who could that girl be? herself, her lost daughter, or the longing to be a mother. The doubt of whether they are memories, programming or desires motivate Venus to travel to the desert to seek answers about the connection with the girl and her own nature.": "Año 2052, Venus despierta sin recuerdos en una ciudad detenida en el tiempo. No sabe si es humana o un robot orgánico. La ausencia de sentimientos la lleva a buscar emociones mediante experimentos perceptivos que le generan visiones vívidas: un bosque frondoso, un caballo blanco y una niña. ¿Quién podría ser esa niña? ¿Ella misma, su hija perdida, o el anhelo de ser madre? La duda de si son recuerdos, programación o deseos impulsa a Venus a viajar al desierto en busca de respuestas sobre su vínculo con la niña y sobre su propia naturaleza.",
"Short essay film about human transformation in the digital age. Recorded during the Covid 19 pandemic in Valdivia and Valparaiso, Chile, the film presents a group of humans dancing in nature and the city. They are the result of the virtual experiment of a group of stage researchers who sought to approach the ecdysis and metamorphosis of insects, as a metaphor for the profound cultural transformation of society by integrating virtuality into everyday life, a questioning of the notion of presence. The voice-over of the process of how a butterfly is born intersects with another voice asking a series of questions about who we are and how we participate in society": "Cortometraje ensayo sobre la transformación humana en la era digital. Registrado durante la pandemia de Covid 19 en Valdivia y Valparaíso, Chile, presenta a un grupo de humanos danzando en la naturaleza y en la ciudad. Son el resultado del experimento virtual de un grupo de investigadores escénicos que buscaron aproximarse a la ecdisis y la metamorfosis de los insectos, como metáfora de la profunda transformación cultural de la sociedad al integrar la virtualidad en la vida cotidiana, un cuestionamiento de la noción de presencia. La voz en off del proceso de cómo nace una mariposa se cruza con otra voz que formula preguntas sobre quiénes somos y cómo participamos en la sociedad",
"An amateur filmmaker attempts to make his first film by recording the real life of a mother and her son: beach, crisis, separation, and a new love with a woman. The film interweaves the images of fiction with fragments of the director’s childhood and behind-the-scenes footage that shows four failed attempts due to lack of resources, experience, ethics, and aesthetics. «Amateurs» reflects on what is essential for a film to exist, and at the same time, a family, two parallel realities that have in common imperfection, authenticity, and passion, components that end up giving life to a cinematographic essay about those who try to create without knowing what it implies to do so.": "Un cineasta amateur intenta hacer su primera película registrando la vida real de una madre y su hijo: playa, crisis, separación y un nuevo amor con una mujer. La película entrelaza las imágenes de ficción con fragmentos de la infancia del director y material de detrás de cámara que muestra cuatro intentos fallidos por falta de recursos, experiencia, ética y estética. «Amateurs» reflexiona sobre qué es lo esencial para que exista una película y, al mismo tiempo, una familia: dos realidades paralelas que comparten imperfección, autenticidad y pasión, componentes que terminan dando vida a un ensayo cinematográfico sobre quienes intentan crear sin saber lo que eso implica.",
"Filmed entirely. Now in development of post-production: With a rough cut, review and re-editing, color grading, and soundtrack review.": "Rodada por completo. En desarrollo de postproducción: con un primer corte, revisión y remontaje, etalonaje y revisión de la banda sonora.",
"Filmed entirely. Now in development of post-production: Writing and recording of voice-over, sound effects, soundtrack, editing, and color grading.": "Rodada por completo. En desarrollo de postproducción: escritura y grabación de voz en off, efectos de sonido, banda sonora, montaje y etalonaje.",
"Filmed entirely. Now in develpment of post-production: Writing and recording of voice-over development.": "Rodada por completo. En desarrollo de postproducción: escritura y grabación de voz en off.",
"Filmed entirely. Now in development of post-production: Voice-over, animated graphic special effects, sound effects, soundtrack, editing, and color grading.": "Rodada por completo. En desarrollo de postproducción: voz en off, efectos gráficos animados, efectos de sonido, banda sonora, montaje y etalonaje."
};
